### ISSUE TITLE
Webpack 2 allows objects as queries

### ISSUE THREAD

**Issue by chrisnicola** [tycho01/pug-plugin-ng#1]
With webpack 2 the following configuration works.

```
      {
        test: /\.pug/,
        include: helpers.root('modules'),
        loader: 'pug-html', 
        query: { plugins: [require('pug-plugin-ng')] },
      },
```

If you have multiple loaders chained it can be written like this.

```
      {
        test: /\.pug/,
        include: helpers.root('modules'),
        loaders: [
          { loader: 'html', query: { root: 'images' } },
          { loader: 'pug-html', query: { plugins: [require('pug-plugin-ng')] }},
        ]
      },
```

Figured you might want to add that to the docs.

**Comment by KiaraGrouwstra** [comment]
So essentially out of the box huh? I'll add that, thanks! :)

**Comment by chrisnicola** [comment]
Pretty much. Though I can't get the html loader to work with the output from `pug-html-loader`. I think it is an issue with `html-loader` though. One battle at a time I guess.

**Comment by KiaraGrouwstra** [comment]
Yeah, tell me about it... I'm glad this obsolifies that `pug-ng-html-loader`, but I wish Ionic 2 RC wouldn't have further complicated Pug use. :(
