### ISSUE TITLE
Webpack 2 configuration issue

### ISSUE THREAD

**Issue by jchatel** [tycho01/pug-plugin-ng#9]
Can't install pug-ng-html-loader, seems like it's incompatible with webpack 2?

pug-ng-html-loader doesn't seem to have issue tracking enabled. So I'm opening an issue here since it's from the same author and this one requires pug-ng-html-loader to be included.

```
ERROR in ./app/javascript/angular-engine/app/admin/page/admin-page.component.ts
Module not found: Error: Can't resolve 'pug-ng-html' in '/Users/Jeremy/work'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'pug-ng-html-loader' instead of 'pug-ng-html',
                 see https://webpack.js.org/migrate/3/#automatic-loader-module-name-extension-removed
```

**Comment by jchatel** [comment]
Moved to "pug-html-loader", seems to work nicely with angular now.

**Comment by KiaraGrouwstra** [comment]
Glad you got this fixed!
Observation: that repo appears not to allow issues since it started as a fork of another repo. Not sure how to fix.
